### ISSUE TITLE
ngx-agora Firefox Audio problem

### ISSUE THREAD

**Issue by caglarturkurka** [drew-thompson/angular-video#1]
Hi, I have a problem about One To One Voice Conferencing via Firefox. Users could not hear theirself. But this problem was not occured Video Conferencing.

**Comment by drew-thompson** [comment]
Hi @caglarturkurka I suggest you contact the folks at [agora.io](https://www.agora.io) for this one. Any browser compatibility issues are dependent on the Agora SDK.
